# Generated by Django 5.1.6 on 2025-03-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nora', '0002_alter_base_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nombre_grupo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
