# Generated by Django 5.1.4 on 2025-02-10 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nora', '0003_retiro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cierres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_cierre', models.IntegerField()),
                ('retiros_cierre', models.IntegerField()),
                ('vEfectivo_cierre', models.IntegerField()),
                ('vNequi_cierre', models.IntegerField()),
                ('vDavip_cierre', models.IntegerField()),
                ('vTotal_cierre', models.IntegerField()),
                ('tCaja_cierre', models.IntegerField()),
                ('obs_cierre', models.CharField(max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
