# Generated by Django 5.1.4 on 2025-02-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nora', '0005_rename_cierres_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cierre',
            name='us_caja',
            field=models.IntegerField(default=5500),
            preserve_default=False,
        ),
    ]
